image: registry.gitlab.com/mailcare/mailcare:latest

stages:
  - test

unit_test:
  stage: test
  script:
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - vendor/bin/phpunit

test_coverage:
  stage: test
  script:
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - vendor/bin/phpunit --coverage-text --colors=never

test_coding_standard:
  stage: test
  script:
    - composer install
    - vendor/bin/phpcs . --ignore="*/vendor/*,*/node_modules/*,*/public/css/*,*/public/js/*,*/database/*,*/autoload.php,*/cache/*,*/*.blade.php,*/storage/*,*/tests/*" --standard=PSR2
