image: registry.gitlab.com/mailcare/mailcare:latest

stages:
  - test

unit_test:
  stage: test
  script:
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - touch database/database_testing.sqlite
    - vendor/bin/phpunit

